import { db } from "@/lib/db";
import {
  discoveredItems,
  autoPostRules,
  campaigns,
  monitoredTopics,
} from "@/lib/db/schema";
import { eq, and, gte, sql, inArray } from "drizzle-orm";
import { campaignQueue } from "@/lib/queue/queues";

interface AutoPostRule {
  id: string;
  topicId: string;
  minRelevanceScore: number | null;
  targetPlatforms: unknown;
  targetPersonaTagIds: unknown;
  maxPostsPerDay: number | null;
  requiresApproval: boolean | null;
  isActive: boolean | null;
  createdAt: Date | null;
  updatedAt: Date | null;
}

/**
 * Process an auto-post for a discovered item that meets a rule's criteria.
 * Called from the relevance-scoring worker after scoring.
 */
export async function processAutoPost(
  discoveredItemId: string,
  rule: AutoPostRule
) {
  // 1. Check daily limit
  const todayStart = new Date();
  todayStart.setHours(0, 0, 0, 0);

  const [dailyCount] = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(discoveredItems)
    .where(
      and(
        eq(discoveredItems.topicId, rule.topicId),
        eq(discoveredItems.status, "auto_posted"),
        gte(discoveredItems.createdAt, todayStart)
      )
    );

  // Also count pending_approval items toward the daily limit
  const [pendingCount] = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(discoveredItems)
    .where(
      and(
        eq(discoveredItems.topicId, rule.topicId),
        eq(discoveredItems.status, "pending_approval"),
        gte(discoveredItems.createdAt, todayStart)
      )
    );

  const totalToday = (dailyCount?.count || 0) + (pendingCount?.count || 0);
  const maxPerDay = rule.maxPostsPerDay ?? 5;

  if (totalToday >= maxPerDay) {
    console.log(
      `Auto-post daily limit reached for topic ${rule.topicId}: ${totalToday}/${maxPerDay}`
    );
    return { skipped: true, reason: "daily_limit_reached" };
  }

  // 2. If requires approval, set status to pending_approval
  if (rule.requiresApproval) {
    await db
      .update(discoveredItems)
      .set({ status: "pending_approval" })
      .where(eq(discoveredItems.id, discoveredItemId));

    console.log(`Item ${discoveredItemId} set to pending_approval (rule ${rule.id})`);
    return { status: "pending_approval", ruleId: rule.id };
  }

  // 3. If no approval required, create and execute campaign automatically
  return await createAndExecuteAutoCampaign(discoveredItemId, rule);
}

/**
 * Create a campaign from a discovered item and queue it for execution.
 */
export async function createAndExecuteAutoCampaign(
  discoveredItemId: string,
  rule: AutoPostRule
) {
  // Fetch the discovered item with its topic
  const [item] = await db
    .select({
      item: discoveredItems,
      topicName: monitoredTopics.name,
      topicUserId: monitoredTopics.userId,
    })
    .from(discoveredItems)
    .innerJoin(monitoredTopics, eq(discoveredItems.topicId, monitoredTopics.id))
    .where(eq(discoveredItems.id, discoveredItemId))
    .limit(1);

  if (!item) {
    throw new Error(`Discovered item not found: ${discoveredItemId}`);
  }

  const aiMeta = (item.item.aiMetadata as Record<string, string>) || {};
  const platforms = (rule.targetPlatforms as string[]) || [];
  const platform = platforms[0] || "twitter";
  const tagIds = (rule.targetPersonaTagIds as string[]) || [];

  // Build content template from the discovered item + AI analysis
  const contentTemplate = [
    `Topic: ${item.topicName}`,
    `Source: ${item.item.title || "Untitled"}`,
    item.item.url ? `Reference: ${item.item.url}` : "",
    item.item.summary ? `Context: ${item.item.summary}` : "",
    aiMeta.suggested_angle ? `Angle: ${aiMeta.suggested_angle}` : "",
    "",
    "Write a natural, engaging post about this topic using the suggested angle. Do not include the reference URL directly - paraphrase and add value.",
  ]
    .filter(Boolean)
    .join("\n");

  // Create campaign + update item status atomically
  const [campaign] = await db.transaction(async (tx) => {
    const [created] = await tx
      .insert(campaigns)
      .values({
        userId: item.topicUserId,
        name: `Auto: ${(item.item.title || "Discovered Item").slice(0, 200)}`,
        description: `Auto-generated campaign from monitoring topic "${item.topicName}" (rule: ${rule.id})`,
        status: "draft",
        targetTagIds: tagIds,
        contentTemplate,
        platform,
        settings: {
          autoGenerated: true,
          discoveredItemId,
          ruleId: rule.id,
          urgency: aiMeta.urgency || "medium",
          delayMin: 1,
          delayMax: 5,
          maxPerPersona: 1,
        },
      })
      .returning();

    await tx
      .update(discoveredItems)
      .set({ status: "auto_posted" })
      .where(eq(discoveredItems.id, discoveredItemId));

    return [created];
  });

  // Queue campaign for execution (outside transaction — side effect)
  await campaignQueue.add(`auto-campaign-${campaign.id}`, {
    campaignId: campaign.id,
    userId: item.topicUserId,
  });

  console.log(
    `Auto-campaign created: ${campaign.id} for item ${discoveredItemId}`
  );

  return { status: "auto_posted", campaignId: campaign.id, ruleId: rule.id };
}

/**
 * Get all items pending approval, with topic and rule info.
 */
export async function getPendingApprovals(userId: string, isAdmin: boolean) {
  const conditions = [eq(discoveredItems.status, "pending_approval")];

  if (!isAdmin) {
    // Only show items for topics owned by this user
    const userTopics = await db
      .select({ id: monitoredTopics.id })
      .from(monitoredTopics)
      .where(eq(monitoredTopics.userId, userId));

    const topicIds = userTopics.map((t) => t.id);
    if (topicIds.length === 0) return [];

    conditions.push(inArray(discoveredItems.topicId, topicIds));
  }

  const items = await db
    .select({
      item: discoveredItems,
      topicName: monitoredTopics.name,
    })
    .from(discoveredItems)
    .innerJoin(monitoredTopics, eq(discoveredItems.topicId, monitoredTopics.id))
    .where(and(...conditions))
    .orderBy(discoveredItems.discoveredAt);

  return items.map((i) => ({
    ...i.item,
    topicName: i.topicName,
  }));
}

/**
 * Approve a pending item - find matching rule and create campaign.
 */
export async function approveItem(itemId: string, userId: string, isAdmin: boolean) {
  // Fetch the item
  const [item] = await db
    .select()
    .from(discoveredItems)
    .where(
      and(
        eq(discoveredItems.id, itemId),
        eq(discoveredItems.status, "pending_approval")
      )
    )
    .limit(1);

  if (!item) {
    return { error: "Item not found or not pending approval" };
  }

  // Verify ownership unless admin
  if (!isAdmin) {
    const [topic] = await db
      .select()
      .from(monitoredTopics)
      .where(
        and(
          eq(monitoredTopics.id, item.topicId),
          eq(monitoredTopics.userId, userId)
        )
      )
      .limit(1);

    if (!topic) {
      return { error: "Not authorized" };
    }
  }

  // Find matching active rule for this topic
  const rules = await db
    .select()
    .from(autoPostRules)
    .where(
      and(
        eq(autoPostRules.topicId, item.topicId),
        eq(autoPostRules.isActive, true)
      )
    );

  // Use the first matching rule (the item was set to pending by one of these)
  const matchingRule = rules.find(
    (r) => (item.relevanceScore ?? 0) >= (r.minRelevanceScore ?? 70)
  );

  if (!matchingRule) {
    // No matching rule found, use a default configuration
    const defaultRule: AutoPostRule = {
      id: "manual-approval",
      topicId: item.topicId,
      minRelevanceScore: 0,
      targetPlatforms: ["twitter"],
      targetPersonaTagIds: [],
      maxPostsPerDay: 999,
      requiresApproval: false,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    };
    return await createAndExecuteAutoCampaign(itemId, defaultRule);
  }

  return await createAndExecuteAutoCampaign(itemId, matchingRule);
}

/**
 * Reject a pending item - set status to "rejected".
 */
export async function rejectItem(itemId: string, userId: string, isAdmin: boolean) {
  const [item] = await db
    .select()
    .from(discoveredItems)
    .where(
      and(
        eq(discoveredItems.id, itemId),
        eq(discoveredItems.status, "pending_approval")
      )
    )
    .limit(1);

  if (!item) {
    return { error: "Item not found or not pending approval" };
  }

  // Verify ownership unless admin
  if (!isAdmin) {
    const [topic] = await db
      .select()
      .from(monitoredTopics)
      .where(
        and(
          eq(monitoredTopics.id, item.topicId),
          eq(monitoredTopics.userId, userId)
        )
      )
      .limit(1);

    if (!topic) {
      return { error: "Not authorized" };
    }
  }

  await db
    .update(discoveredItems)
    .set({ status: "rejected" })
    .where(eq(discoveredItems.id, itemId));

  return { status: "rejected", itemId };
}
